export const proOffer=[    {
        id:1,
        Name:"P55 5G",
        desc:"itel P55 5G | Dimensity 6080 | 12GB* RAM+128GB ROM with Memory Fusion| 50MP AI Dual Rear Camera| 5000mAh Battery | 2 Years Warranty | Mint Green",
        price: 13500,
        discountprice: 10000,
        discountpercent: "30%",
        image: "./Assets/Home/ProductOffer/Offpro1.jpg" ,
       },
       {
        id:2,
        Name:"Hair Dryer",
        desc:"Havells HD3181 1600 Watts Unisex Foldable Hair Dryer; 3 Heat (Hot/Warm/Cold) Settings including Cool Shot Button; Heat Balance Technology (Black)",
        price: 2000,
        discountprice: 1399,
        discountpercent: "30%",
        image: "./Assets/Home/ProductOffer/Offpro2.jpg" ,
       },
       {
        id:3,
        Name:"Djokr Perfume",
        desc:"Djokr Perfume Gift Set for Men Pack of 4x20 ML | Eau De Parfum | Premium Luxury Long Lasting Fragrance Spray | Signature, Wicked, Oud Wood, Marine ( 4x20 ml)",
        price: 849,
        discountprice: 499,
        discountpercent: "41%",
        image: "./Assets/Home/ProductOffer/Offpro3.jpg" ,
       },
       {
        id:4,
        Name:"Zeb-Jet PRO",
        desc:"Zebronics Jet PRO Premium Wired Gaming On Ear Headphone with LED for Headband + earcups, 40mm Neodymium Drivers, 2 Meter Braided Cable, with mic, Suspension Design, 3.5mm + USB Connector (Black, Blue)",
        price: 1899,
        discountprice: 799,
        discountpercent: "58%",
        image: "./Assets/Home/ProductOffer/Offpro4.jpg" ,
       },
       {
        id:5,
        Name:"Projector",
        desc:"XGIMI Horizon Pro 4K Projector, 2200 ANSI Lumens, Android TV 10.0 Movie Projector with Integrated Harman Kardon Speakers, Auto Keystone Screen Adaption Home Theater Projector with WiFi Bluetooth",
        price: 299900,
        discountprice: 139999,
        discountpercent: "53%",
        image: "./Assets/Home/ProductOffer/Offpro5.jpg" ,
       },
       {
        id:6,
        Name:"Mini Projector",
        desc:"Anker NEBULA Apollo, Wi-Fi Mini Projector, 200 ANSI Lumen Portable Projector, 6W Speaker, Movie Projector, 100 Inch Picture, 4Hr Video Playtime, Neat Projector, Home Entertainment—Watch Anywhere",
        price: 49900,
        discountprice: 34999,
        discountpercent: "30%",
        image: "./Assets/Home/ProductOffer/Offpro6.jpg" ,
       },
       {
        id:7,
        Name:"Clapbox",
        desc:"Clapbox Adjustable Snare Cajon CB40- Blue, Birch Wood (H:50 W:30 L:30) - 3 Internal Snares",
        price: 12999,
        discountprice: 4199,
        discountpercent: "68%",
        image: "./Assets/Home/ProductOffer/Offpro7.jpg" ,
       },
       {
        id:8,
        Name:"sneaker",
        desc:"Woodland Mens Gc 1869115nw Sneaker",
        price: 4195,
        discountprice: 3943,
        discountpercent: "6%",
        image: "./Assets/Home/ProductOffer/Offpro8.jpg" ,
       },
       {
        id:9,
        Name:"Room Heater",
        desc:"Longway Blaze 2 Rod 800-Watts Quartz Heater | Room Heater | 1 Year Warranty (White and Grey)",
        price: 2199,
        discountprice: 899,
        discountpercent: "59%",
        image: "./Assets/Home/ProductOffer/Offpro9.jpg" ,
       },
       {
        id:10,
        Name:"Hand Bag",
        desc:"Lavie Women's Ushawu Small Satchel Bag | Ladies Purse Handbag",
        price: 4199,
        discountprice: 1222,
        discountpercent: "71%",
        image: "./Assets/Home/ProductOffer/Offpro10.jpg" ,
       },
]